# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0-beta3"
manifest_format = "2.0"
project_hash = "68d87c2b782f39346e042b6c4843f9f03b095a18"

[[deps.Foo]]
path = "Foo"
uuid = "d0564559-5b47-4c7c-871f-02a065a21f8c"
version = "0.1.0"
