# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0-beta3"
manifest_format = "2.0"
project_hash = "a91c28a15dbcd28414367b3b44524a2d39c4521d"

[[deps.Foo]]
path = "Foo"
uuid = "3fd9b0fe-f817-4e6b-be18-d9e347fda0f6"
version = "0.1.0"
