# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0-beta3"
manifest_format = "2.0"
project_hash = "66d08595bfd35c3ebdddcd00f0b392efc0bcc680"

[[deps.Foo]]
path = "Foo"
uuid = "45a4483b-101e-48f7-ac5b-b0339c1234a9"
version = "0.1.0"
